---
- name: Targeting the host
  hosts: g1
  become: yes

  tasks:
   - name: unzip
     yum:
       name: unzip
       state: present

  tasks:
   - name: Install AWS CLI
     package:
       name: awscli
       state: present

...