---
- name: Targeting the host
  hosts: g1
  become: yes
  gather_facts: false

  tasks:
   - name: unzip
     yum:
       name: unzip
       state: present

  
   - name: Install AWS CLI'
     package:
       name: awscli
       state: present

   - name: download and install the kops 
     shell: |
      curl -Lo kops https://github.com/kubernetes/kops/releases/download/$(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4)/kops-linux-amd64
      chmod +x kops
      sudo mv kops /usr/local/bin/kops


   - name: Downloading KUBECTL
     get_url:
      url: https://dl.k8s.io/release/v1.26.1/bin/linux/amd64/kubectl
      dest: /usr/local/bin/kubectl
      
   - name: kubectl pathway
     command: chmod +x /usr/local/bin/kubectl

   - name: creating a cluster
     shell: |
      kops create cluster --state=s3://k8-project-10002 --zones=us-east-1a,us-east-1b --node-count=2 --name=project.k8s.local --yes --ssh-public-key=/home/centos/key.pub

...


         


...