---
- name: Targeting the host
  hosts: g1
  become: yes

  tasks:
   - name: unzip
     yum:
       name: unzip
       state: present

  tasks:
   - name: Install AWS CLI
     package:
       name: awscli
       state: present


  - name: Install kops
  hosts: all
  become: yes
  tasks:
  - name: Download kops binary
    get_url:
      url: https://github.com/kubernetes/kops/releases/download/{{ kops_version }}/kops-linux-amd64
      dest: /root/kops
    vars:
      kops_version: "1.20.0"
  - name: Make kops executable
    file:
      path: /root/kops
      mode: 0755
  - name: Link kops to /usr/local/bin
    file:
      src: /root/kops
      dest: /usr/local/bin/kops
      state: link

...