---
- name: Targeting the host
  hosts: g1
  become: yes

  tasks:
   - name: unzip
     yum:
       name: unzip
       state: present

  
   - name: Install AWS CLI'
     package:
       name: awscli
       state: present

  
   - name: install pip
     package: 
      name: python3-pip
      state: present
      

  
   - name: Install KOPS
     yum:
      name: kops
      state: present

   - name: Install KUBECTL
     shell: |
      curl -LO https://dl.k8s.io/release/stable.txt
      VERSION=$(cat stable.txt)
      curl -LO https://dl.k8s.io/$VERSION/bin/linux/amd64/kubectl
      chmod +x kubectl
      sudo mv kubectl /usr/local/bin/
         


...