---
- name: Targeting the host
  hosts: g1
  become: yes

  tasks:
   - name: unzip
     yum:
       name: unzip
       state: present

  tasks:
   - name: Install AWS CLI
     package:
       name: awscli
       state: present

  tasks:
  - name: Download kops binary
    shell: |
      curl -Lo kops https://github.com/kubernetes/kops/releases/download/$(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4)/kops-darwin-amd64
    args:
      chdir: /root
  - name: Make kops executable
    file:
      path: /root/kops
      mode: 0755
  - name: Move kops to /usr/local/bin
    file:
      src: /root/kops
      dest: /usr/local/bin/kops
      state: link
...