---
- name: Targeting the host
  hosts: g1
  become: yes

  tasks:
   - name: unzip
     yum:
       name: unzip
       state: present

  
   - name: Install AWS CLI'
     package:
       name: awscli
       state: present

  
   - name: install pip
     package: 
      name: python3-pip
      
   - name: Install KOPS directly
     pip:
      name: kops
      state: present




         


...