---
- name: Targeting the host
  hosts: g1
  become: yes

  tasks:
   - name: unzip
     yum:
       name: unzip
       state: present

  tasks:
   - name: Install AWS CLI
     package:
       name: awscli
       state: present


  tasks:
    - name: Download and install kops
      command: curl -Lo kops https://github.com/kubernetes/kops/releases/download/$(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4)/kops-linux-amd64
      register: kops_download
      changed_when: kops_download.rc != 0
      
    - name: Install kops binary
      command: chmod +x kops && sudo mv /usr/local/bin/kops
      when: kops_download.rc == 0

  tasks: 
    - name: Download and install kubectl
      command: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      register: kubectl_download
      changed_when: kubectl_download.rc != 0
      
    - name: Install kubectl binary
      command: chmod +x kubectl && sudo mv kubectl /usr/local/bin/kubectl
      when: kubectl_download.rc == 0

...