---
- name: Targeting the host
  hosts: g1
  become: yes
  gather_facts: false

  tasks:
   - name: unzip
     yum:
       name: unzip
       state: present

  
   - name: Install AWS CLI'
     package:
       name: awscli
       state: present

   - name: download kops 
     get_url: 
      url: https://github.com/kubernetes/kops/releases/download/v1.25.3/kops-darwin-arm64
      dest: /usr/local/bin/kops

   - name: execute kops
     command: chmod +x /usr/local/bin/kops



         


...