---
- name: Targeting the host
  hosts: g1
  become: yes

  tasks:
   - name: unzip
     yum:
       name: unzip
       state: present

  tasks:
   - name: Install AWS CLI
     package:
       name: awscli
       state: present

  tasks:
  - name: install pip
    yum: 
      name: python3-pip
      state: present

  tasks:
  - name: install kops directly
    pip: 
       name: kops
       state: present
         


...