---
- name: Targeting the host
  hosts: g1
  become: yes
  gather_facts: false

  tasks:
   - name: unzip
     yum:
       name: unzip
       state: present

  
   - name: Install AWS CLI'
     package:
       name: awscli
       state: present

   - name: download kops 
     get_url: 
      url: https://github.com/kubernetes/kops/releases/tag/v1.25.3/kops-linux-amd64
      dest: /usr/local/sbin/kops

   - name: execute kops
     command: chmod 0664 /usr/local/sbin/kops
     warn:    false
     command: chmod +x /usr/local/sbin/kops



         


...