---
- name: Targeting the host
  hosts: g1
  become: yes

  tasks:
   - name: unzip
     yum:
       name: unzip
       state: present

  tasks:
   - name: Install AWS CLI
     package:
       name: awscli
       state: present


  tasks:
  - name: Download kops binary
    get_url:
      url: https://github.com/kubernetes/kops/releases/download/v1.26.0-beta.1/kops-linux-amd64
      dest: /home/centos
    
  - name: Make kops executable
    command: chmod +x kops
    command: sudo mv kops /usr/local/bin/kops

...