---
- name: Targeting the host
  hosts: g1
  become: yes

  tasks:
   - name: unzip
     yum:
       name: unzip
       state: present

  tasks:
   - name: Install AWS CLI
     package:
       name: awscli
       state: present


  tasks:
    - name: Download kops binary
      shell: curl -LO https://dl.k8s.io/release/1.20.0/bin/linux/amd64/kops
      args:
      executable: /bin/bash
    - name: Make kops binary executable
      file:
        path: /usr/local/bin/kops
        state: link
        src: /root/kops
        owner: root
        group: root
        mode: 0755

        
...