# Service object to Access Application

apiVersion: v1
kind: Service
metadata: 
  name: calculator-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: calc



